name: Run Databricks Notebook

on:
  push:
    branches:
      - main

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Databricks Notebook
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}
        DATABRICKS_NOTEBOOK_PATH: '/Users/merajalam@in.bosch.com/Notebook-V1'
      run: |
        curl -X POST -H "Authorization: Bearer $DATABRICKS_TOKEN" -H "Content-Type: application/json" \
          -d '{"cluster_id":"'$DATABRICKS_CLUSTER_ID'","notebook_task":{"notebook_path":"'$DATABRICKS_NOTEBOOK_PATH'"}}' \
          "https://$DATABRICKS_HOST/api/2.0/jobs/run-now"
